import type { Metadata } from "next";
import "./globals.css";

import Footer from "./Footer";
import { Suspense } from "react";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params, // Access route parameters to get locale
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string }; // Ensure params contains locale
}>) {
  const messages = await getMessages(); 
  const currentLocale = params.locale; // Get the current locale

  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={currentLocale} dir={currentLocale === 'ar' ? 'rtl' : 'ltr'}>
        <body>
          <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
          <Footer />
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
